import time

n = time.time()

s = "dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;dads;asdasdas;d;asd;as;d;as;d;asd;as;d;as;d;asd;d;as;sa;f;saf;sd;fsd;f;grth;u;yt;uy;yi;yui;yt;bt;uj;vy;y;yu;ty;uty;buv;;;t;;t;y;y;yyuy;niuy;mi;uymi;o;uim,o;u;"
# print(len(s))
x = s.split(";")
print((time.time() - n) * 1000, "ms")
for i in x:
    if i.lower() == "btc":
        pass
print((time.time() - n) * 1000, "ms")
